import type {TableValue} from '../ExcelImporter/types'

// A chart generated by a parser
export interface GeneratedGrafica {
  titulo: string
  tipo: 'bar' | 'line' | 'doughnut' | 'pie' | 'horizontalBar' | 'table'
  ubicacion: string[]
  tablaDatos: TableValue
  unidadMedida?: string
  fuente?: string
  fuentePersonalizada?: string
  descripcionContexto?: string
  series?: {
    nombre: string
    tipoSerie: 'line' | 'bar'
    color?: string
    ejeSecundario?: boolean
  }[]
}

// A parser function: receives the raw Excel workbook and returns charts
export type IndicadorParser = (workbook: any) => GeneratedGrafica[]

// Result of an import operation
export interface ImportResult {
  graficas: GeneratedGrafica[]
  warnings: string[]
}
